create database KidsLand;
use KidsLand;

create table Personne (user_id INT AUTO_INCREMENT, user_name VARCHAR(20), user_age INT, user_pseudo VARCHAR(20), user_login VARCHAR(20), user_type VARCHAR(10), member_type VARCHAR(10), image VARCHAR(300), PRIMARY KEY (user_id));
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Jerome Davido", 42, "jdavido@gmail.com", "jdavido", "MC", "regular", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Member_Homme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Stéphanie Durand", 37, "sdurand@gmail.com", "sdurand", "E", "NULL", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Employee_Homme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Véronique Rivaud", 40, "NULL", "NULL", "GC", "NULL", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Guest_Femme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Clémence Dirma", 70, "NULL", "NULL", "GC", "NULL", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Guest_Femme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Jérémy Pied", 78, "NULL", "NULL", "GC", "NULL", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Member_Homme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Yusuf Yazici", 28, "yyazici@gmail.com", "yyazici", "MC", "regular", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Member_Homme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Antoine Fourneau", 12, "anto2@yahoo.fr", "ratoZaure", "MC", "children", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Member_Homme.jpg");
insert into Personne (user_name, user_age, user_pseudo, user_login, user_type,member_type, image) values ("Jean-Jacques Buy", 55, "joano@gmail.com", "joana", "E", "NULL", "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Personnes\\Employee_Homme.jpg");

create table Ride (id_ride INT AUTO_INCREMENT, name_ride VARCHAR(20), price_ride DOUBLE, features_ride VARCHAR(300), max_tickets INT, image VARCHAR(300) ,PRIMARY KEY (id_ride));
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("SpeedLand Express", 6.75,"Extreme speed, not recommended for shy people. Strong sensations guaranteed. Forbidden for less than 1m50", 16,  "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\SpeedLandExpress.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("AquaImmersion", 4.5,"Get ready to be soaked! Accessible to everyone. Average speed", 14, "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\AquaImmersion.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("GhostTerror", 5,"Don’t be afraid! Thrills guaranteed in this ghost train. Very dark ride", 20, "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\GhostTerror.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("FlyingChairs",4,"Find the famous flying chairs in this ride for children. Average flying height", 14, "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\FlyingChairs.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("ExtremeLand", 7,"The most extreme attraction of the park! Maximum speed of 100km/h. Several looping and very big thrills. Prohibited under 1m60", 18, "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\ExtremeLand.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("Giga Bumper-car", 5.5,"Giga bumper car for any level! Session duration: 3 minutes", 25, "C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\GigaBumper-car.jpg");
insert into Ride (name_ride, price_ride, features_ride, max_tickets) values ("TurnOver", 8.25,"Forbidden for less than 16 years old !", 25,"C:\Users\\lonyf\\OneDrive\\Documents\\ECE 2020\\Project-Databases\\Application\\Images\\Attractions\\TurnOver.jpg");

create table Command (id_command INT AUTO_INCREMENT, ride_command INT, user_command INT, adult_ticket INT, child_ticket INT, date_command Date, date_purchase Date, total_price DOUBLE, PRIMARY KEY (id_command), CONSTRAINT fk_ride_id FOREIGN KEY (ride_command) REFERENCES Ride(id_ride), CONSTRAINT fk_user_id FOREIGN KEY (user_command) REFERENCES Personne(user_id));
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (2, 3, 2 , 1, "2021-01-12" + "2020-12-14" +  18);
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (1, 14, 0 , 3, "2020-12-27" + "2020-12-17" +  22.22);
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (4, 24, 3 , 0, "2021-02-01" + "2020-12-11" + 16);
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (6, 10, 1 , 2, "2020-12-20" + "2020-11-29" +  10);
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (3, 3, 37, 4 , 4, "2020-12-27" + "2020-12-10" +  42.4);
insert into Command  (ride_command, user_command, adult_ticket, child_ticket, date_command, date_purchase, total_price) values (5, 18, 1 , 1, "2021-01-10" + "2020-12-02" +  8);